## firmware.cpp

The `firmware.cpp` file contains the firmware running on the ESP32-S3 and acts as the bridge between the Raspberry Pi and the connected computer.

Its primary responsibility is to receive commands from the Raspberry Pi, interpret them, and execute them as Human Interface Device (HID) actions such as keyboard presses, mouse movements, clicks, and shortcuts.

### Responsibilities

* Establish communication with the Raspberry Pi
* Receive and parse incoming commands
* Emulate keyboard and mouse actions
* Execute workflow steps generated by the AI
* Manage peripheral devices connected to the ESP32
* Provide status feedback to the main system
* Ensure reliable execution of HID commands

### Current Features

* USB HID keyboard emulation
* USB HID mouse emulation
* Command parsing
* Serial communication
* Task execution interface

### Future Improvements

* Wireless communication support
* OTA firmware updates
* Error recovery mechanisms
* Peripheral expansion support
* Real-time status monitoring
* Multi-device control support

This firmware serves as the action layer of Nexis, allowing the AI system to physically interact with and control a connected computer.
